### PR TITLE
configure executable jar packaging

### PR DESCRIPTION
**Pull request by pmaria**

### CODE REVIEW

**Comment by architolk** [comment]
Hi Pano,

This looks like the same way of making the jar executable as the pebble example application. The instructions to make that one runnable was using mvn. I tried that one using "java -jar". This works (kinda): the application starts, but the context seems different (files cannot be found)

**Comment by pmaria** [comment]
Ah right, it will look for the config at `file:/config/rdftemplate.yml`, which is fine for some dockerized apps, but not very flexible. I'll see if I can make the path relative.

**Comment by pmaria** [comment]
@architolk added the relative location lookup as well.
So now, the app will first look for a config folder in the same directory as the jar. If not found it will look for it at the file system root, if not found it will look for it on the classpath root.

**Comment by pmaria** [comment]
@architolk @Bakkej can I merge this?

**Review by Bakkej — APPROVED** [review]

**Pull request merged**
